import React, { useState } from 'react';
import { EditPlan, EditPlanItem } from '../types';
import { FileEdit, Check, X, ArrowRight, Trash2, Plus, RefreshCw, AlertCircle } from 'lucide-react';

interface EditPlanModalProps {
  plan: EditPlan | null;
  originalContents: Record<string, string>;
  onApply: (selectedEdits: EditPlanItem[]) => void;
  onDiscard: () => void;
}

export const EditPlanModal: React.FC<EditPlanModalProps> = ({
  plan,
  originalContents,
  onApply,
  onDiscard,
}) => {
  if (!plan) return null;
  const edits: EditPlanItem[] = plan.edits || [];

  const [selectedPaths, setSelectedPaths] = useState<Record<string, boolean>>(() => {
    const initial: Record<string, boolean> = {};
    edits.forEach((e: EditPlanItem) => {
      initial[e.path] = true;
    });
    return initial;
  });

  const [activeDiffPath, setActiveDiffPath] = useState<string>(edits[0]?.path || '');

  const toggleSelect = (path: string) => {
    setSelectedPaths((prev) => ({ ...prev, [path]: !prev[path] }));
  };

  const handleApply = () => {
    const kept = edits.filter((e: EditPlanItem) => selectedPaths[e.path]);
    onApply(kept);
  };

  const activeEdit = edits.find((e: EditPlanItem) => e.path === activeDiffPath) || edits[0];
  const original = activeEdit ? originalContents[activeEdit.path] || '' : '';
  const proposed = activeEdit?.content || '';

  const getOpBadge = (op: string) => {
    switch (op) {
      case 'create':
        return <span className="bg-emerald-950 text-emerald-400 border border-emerald-700/50 px-1.5 py-0.5 rounded text-[10px] font-mono flex items-center gap-1"><Plus className="w-2.5 h-2.5" /> CREATE</span>;
      case 'delete':
        return <span className="bg-red-950 text-red-400 border border-red-700/50 px-1.5 py-0.5 rounded text-[10px] font-mono flex items-center gap-1"><Trash2 className="w-2.5 h-2.5" /> DELETE</span>;
      case 'rename':
        return <span className="bg-purple-950 text-purple-400 border border-purple-700/50 px-1.5 py-0.5 rounded text-[10px] font-mono flex items-center gap-1"><RefreshCw className="w-2.5 h-2.5" /> RENAME</span>;
      default:
        return <span className="bg-blue-950 text-blue-400 border border-blue-700/50 px-1.5 py-0.5 rounded text-[10px] font-mono flex items-center gap-1"><FileEdit className="w-2.5 h-2.5" /> UPDATE</span>;
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4">
      <div
        id="edit-plan-modal"
        className="w-full max-w-5xl h-[85vh] bg-[#252526] border border-[#3c3c3c] rounded-xl shadow-2xl flex flex-col overflow-hidden text-xs text-[#cccccc]"
      >
        {/* Header */}
        <div className="h-12 px-4 bg-[#323233] border-b border-[#3c3c3c] flex items-center justify-between shrink-0">
          <div className="flex items-center gap-2">
            <FileEdit className="w-5 h-5 text-amber-400" />
            <div>
              <h2 className="font-semibold text-white text-sm">Review Proposed Edit Plan</h2>
              <p className="text-[11px] text-[#858585] truncate max-w-xl">{plan.summary || 'Structured edits generated by Local Ollama'}</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={onDiscard}
              className="px-3 py-1.5 rounded bg-[#3c3c3c] hover:bg-[#484848] text-white transition-colors"
            >
              Discard All
            </button>
            <button
              onClick={handleApply}
              className="px-4 py-1.5 rounded bg-blue-600 hover:bg-blue-500 font-semibold text-white transition-colors flex items-center gap-1.5"
            >
              <Check className="w-4 h-4" />
              <span>Apply Selected ({Object.values(selectedPaths).filter(Boolean).length})</span>
            </button>
          </div>
        </div>

        {/* Content area: left list, right diff */}
        <div className="flex-1 flex overflow-hidden">
          {/* File list */}
          <div className="w-80 bg-[#1e1e1e] border-r border-[#333333] flex flex-col shrink-0">
            <div className="p-2 border-b border-[#333333] text-[11px] font-bold text-[#888888] uppercase tracking-wider">
              Candidate Files ({edits.length})
            </div>

            <div className="flex-1 overflow-y-auto p-2 space-y-1.5">
              {edits.map((edit: EditPlanItem) => {
                const isSelected = !!selectedPaths[edit.path];
                const isActive = edit.path === activeDiffPath;
                return (
                  <div
                    key={edit.path}
                    onClick={() => setActiveDiffPath(edit.path)}
                    className={`p-2 rounded-lg cursor-pointer transition-colors border ${
                      isActive
                        ? 'bg-[#2a2d2e] border-blue-500 text-white'
                        : 'bg-[#252526] border-[#333333] hover:border-[#444444]'
                    }`}
                  >
                    <div className="flex items-center justify-between mb-1">
                      <div className="flex items-center gap-1.5 font-mono text-[11px] font-semibold truncate">
                        {edit.path}
                      </div>
                      <input
                        type="checkbox"
                        checked={isSelected}
                        onChange={(e) => {
                          e.stopPropagation();
                          toggleSelect(edit.path);
                        }}
                        className="accent-blue-500 cursor-pointer"
                        title={isSelected ? 'Keep this edit' : 'Discard this edit'}
                      />
                    </div>

                    <div className="flex items-center gap-1.5 mt-1">
                      {getOpBadge(edit.operation || 'update')}
                      {edit.newPath && (
                        <span className="text-[10px] text-neutral-400 truncate">→ {edit.newPath}</span>
                      )}
                    </div>

                    {edit.summary && (
                      <p className="text-[10px] text-neutral-400 mt-1 line-clamp-2">
                        {edit.summary}
                      </p>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Diff View */}
          <div className="flex-1 flex flex-col bg-[#1e1e1e] overflow-hidden">
            {activeEdit ? (
              <>
                <div className="h-8 px-4 bg-[#252526] border-b border-[#333333] flex items-center justify-between text-xs">
                  <span className="font-mono text-white font-medium">{activeEdit.path}</span>
                  <div className="flex items-center gap-4 text-[11px] text-[#888888]">
                    <span className="flex items-center gap-1"><span className="w-2.5 h-2.5 bg-red-900/80 rounded" /> Original</span>
                    <span className="flex items-center gap-1"><span className="w-2.5 h-2.5 bg-emerald-900/80 rounded" /> Proposed</span>
                  </div>
                </div>

                <div className="flex-1 grid grid-cols-2 overflow-hidden font-mono text-xs divide-x divide-[#333333]">
                  {/* Original */}
                  <div className="flex flex-col overflow-hidden">
                    <div className="p-1.5 bg-[#201515] text-red-300 text-[10px] font-bold border-b border-[#333333]">
                      ORIGINAL FILE CONTENT
                    </div>
                    <pre className="flex-1 overflow-auto p-3 text-[11px] text-[#d4d4d4] whitespace-pre bg-[#181818]">
                      {original || '(Empty or new file)'}
                    </pre>
                  </div>

                  {/* Proposed */}
                  <div className="flex flex-col overflow-hidden">
                    <div className="p-1.5 bg-[#142318] text-emerald-300 text-[10px] font-bold border-b border-[#333333]">
                      PROPOSED REVISION
                    </div>
                    <pre className="flex-1 overflow-auto p-3 text-[11px] text-[#d4d4d4] whitespace-pre bg-[#161a17]">
                      {proposed || '(File will be deleted)'}
                    </pre>
                  </div>
                </div>
              </>
            ) : (
              <div className="flex-1 flex items-center justify-center text-neutral-500">
                No edit selected
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
